# Generated by Django 4.2.9 on 2024-04-22 15:30

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='price',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
