# Generated by Django 4.2.9 on 2024-05-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='additional_infos',
            field=models.TextField(blank=True),
        ),
    ]
