# Generated by Django 4.2.9 on 2024-04-28 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='id',
            field=models.CharField(default=uuid.UUID('eb2af3b5-2261-433f-9894-0c08eed3af5c'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
