# Generated by Django 4.2.9 on 2024-04-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_businessinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='id',
            field=models.CharField(default='5af66de3-2695-4532-9835-ac32af170dbf', max_length=100, primary_key=True, serialize=False),
        ),
    ]
