# Generated by Django 4.2.9 on 2024-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestion',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
