# Generated by Django 4.2.9 on 2024-05-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestion', '0002_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestion',
            name='category',
        ),
        migrations.AlterField(
            model_name='requestion',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestions', to='requestion.subcategory'),
        ),
    ]
