# Generated by Django 4.2.9 on 2024-04-28 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestion', '0002_requestion_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('e3f619a9-81f2-42bc-b885-20e774b6c039'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
