# Generated by Django 4.2.9 on 2024-04-28 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestion', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('0b35ce43-5a37-40d5-8396-d46db1f47672'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
