# Generated by Django 4.2.9 on 2024-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestion', '0003_remove_requestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestion',
            name='image',
            field=models.ImageField(default='requestion.jpg', null=True, upload_to='reqimages'),
        ),
    ]
