# Generated by Django 4.2.9 on 2024-04-28 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requestion', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.UUID('c6342e7b-28af-402e-8c71-73e4594175bc'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
